name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      cloudfront_assets_version: ${{ steps.set_version.outputs.cloudfront_assets_version }}
    steps:
      - uses: actions/checkout@v4
      - id: set_version
        run: |
          TIMESTAMP=$(date +%Y%m%d%H%M)
          VERSION=$(git rev-parse --short HEAD)
          echo "cloudfront_assets_version=${TIMESTAMP}_${VERSION}" >> $GITHUB_OUTPUT
      - uses: ./.github/actions/build

  lint-and-type-check:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build
      - name: Lint
        run: pnpm check:lint
      - name: Type check
        run: pnpm check:type

  test:
    needs: lint-and-type-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build
      - name: Run tests
        run: pnpm test

  deploy:
    # if: github.ref == 'refs/heads/main' && github.repository_owner == 'peacefulseeker'
    needs: [build, test]
    runs-on: ubuntu-latest
    env:
      CLOUDFRONT_ASSETS_VERSION: ${{ needs.build.outputs.cloudfront_assets_version }}
    outputs:
      cloudfront_assets_version: ${{ env.CLOUDFRONT_ASSETS_VERSION }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      - name: Deploy to S3
        run: |
          aws s3 sync dist/ s3://django-libraryms/v/${{ env.CLOUDFRONT_ASSETS_VERSION }} --acl public-read

  create-release:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG_NAME="v${{ needs.deploy.outputs.cloudfront_assets_version }}"
          gh release create $TAG_NAME \
            --title "Release $TAG_NAME" \
            --notes "Automated release for version $TAG_NAME" \
            --target ${{ github.sha }}
