name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20.9.0

    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 9.9.0

    - name: Install dependencies
      run: pnpm install

    - name: Generate version number
      id: version
      run: echo "::set-output name=version::$(git rev-parse --short HEAD)"

    - name: build
      run: CLOUDFRONT_ASSETS_VERSION=${{ steps.version.outputs.version }} pnpm run build

    - name: lint
      run: pnpm run lint

    - name: type check
      run: pnpm run type-check

    - name: Run tests
      run: pnpm run test

    - name: Authorize AWS
      if: github.ref == 'refs/heads/main' && github.repository_owner == 'peacefulseeker'
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1

    - name: Deploy to S3
      run: |
        VERSION=${{ steps.version.outputs.version }}
        aws s3 sync dist/ s3://django-libraryms/v/$VERSION --delete --acl public-read
        # aws cloudfront create-invalidation --distribution-id YOUR_DISTRIBUTION_ID --paths "/v/$VERSION/*"
