name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  GITHUB_CONTEXT: ${{ toJson(github) }}

jobs:
  generate-assets-version:
    runs-on: ubuntu-latest
    outputs:
      cloudfront_assets_version: ${{ steps.set_version.outputs.cloudfront_assets_version }}
    steps:
      - uses: actions/checkout@v4
      - id: set_version
        run: |
          TIMESTAMP=$(date +%Y%m%d%H%M)
          VERSION=$(git rev-parse --short HEAD)
          echo "cloudfront_assets_version=${TIMESTAMP}_${VERSION}" >> $GITHUB_OUTPUT

  build:
    needs: generate-assets-version
    runs-on: ubuntu-latest
    env:
      GEN_ASSETS_OUTPUTS: ${{join(needs.generate-assets-version.outputs.*, '\n')}}
      CLOUDFRONT_ASSETS_VERSION: ${{ needs.generate-assets-version.outputs.cloudfront_assets_version }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build

  lint-and-type-check:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build
      - name: Lint
        run: pnpm check:lint
      - name: Type check
        run: pnpm check:type

  test:
    needs: lint-and-type-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build
      - name: Run tests
        run: pnpm test

  deploy:
    needs: [generate-assets-version, test]
    runs-on: ubuntu-latest
    env:
      CLOUDFRONT_ASSETS_VERSION: ${{ needs.generate-assets-version.outputs.cloudfront_assets_version }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      - name: Deploy to S3
        run: |
          aws s3 sync dist/ s3://django-libraryms/v/${{ env.CLOUDFRONT_ASSETS_VERSION }} --acl public-read
